framework:
  github: amirfaramarzi/tower
  version: 1.18

build_deps:
  - libevent-dev
  - openssl-dev

environment:
  CFLAGS: "$CFLAGS -D_GNU_SOURCE"
  
php_mod:
  - pcntl
  - sockets

php_ext:
  - event
  - redis

before_command:
  - mkdir storage/logs -p

command: php server.php start
