framework:
  github: amirfaramarzi/tower
  version: 1.14

  build_deps:
    - libevent-dev
    - openssl-dev

  modules:
    - pcntl
    - sockets

  extensions:
    - event
    - redis

  bootstrap:
    - mkdir storage/logs -p

  command: php server.php start
