provider:
  default:
    language: 8.0

sources:
  - "**/*.cs"

binaries:
  - out

environment:
  ASPNETCORE_URLS: http://*:3000
  COMPlus_TieredCompilation: 1

deps:
  - aspnetcore-runtime-3.1

command: /usr/bin/dotnet /opt/web/out/aspnetcore.dll

docker_pause: 15
