framework:
  github: dutradda/apidaora
  version: 0.28

deps:
  - "@development-tools"
  - python3
  - python3-devel
  - python3-pip
  - libffi-devel
  - curl
  - openssl-devel

alpine-deps:
  - curl
  - libffi-dev
  - curl
  - openssl-dev

bootstrap:
  - curl https://sh.rustup.rs > init.sh
  - sh init.sh -y
  - rustup default nightly
  - cd /opt/web && /usr/local/bin/python -m pip install -r requirements.txt -U

files:
  - server.py
  - requirements.txt
  - ../.config/gunicorn.py

environment:
  RUSTFLAGS: -C target-feature=-crt-static
  WORKER_CLASS: uvicorn.workers.UvicornWorker
