framework:
  website: srfnstack.github.io/spliffy/
  github: SRFNStack/spliffy
  version: 0.8

build_deps:
  - git

bin_deps:
  - gcompat # required by uWebSocket

files:
  - app.js
  - package.json
  - www/