framework:
  website: armeria.dev
  version: 1.34

  build:
    - mvn package

  files:
    - target/benchmark.jar

  binaries:
    - target/benchmark.jar

  command: /usr/bin/java -jar /opt/web/target/benchmark.jar
