framework:
  github: luoxiaojun1992/sw-fw-less
  version: preview

php_ext:
  - swoole

php_mod:
  - sockets

deps:
  - php
  - composer
  - "@development-tools"
  - php-pear
  - php-devel
  - php-bcmath

command: /usr/bin/php /opt/web/start.php
