framework:
  github: aplus-framework/one
  version: 23.0
  website: aplus-framework.com/packages/one

  build_deps:
    - libsodium-dev
    - memcached
    - libmemcached-tools
    - libmemcached-dev 
    - libyaml-dev
    - libicu-dev
    - libpng-dev

  modules:
    - sodium
    - mysqli
    - intl
    - gd

  extensions:
    - igbinary
    - memcached
    - msgpack
    - redis
    - yaml
