framework:
  website: spring.io/projects/spring-boot
  version: 3.0

  binaries:
    - target/benchmark-1.0.0.jar

  command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC  -jar /opt/web/target/benchmark-1.0.0.jar
