# Exit build if no modification found
before_install: bash .ci/has_to_run.sh || travis_terminate 0

services:
  - docker # Use docker to containerize frameworks
  - postgresql # Use postgresql to store data

dist: bionic

# This tool is written in crystal
language: crystal

env:
  global:
    - DATABASE_URL=postgresql://postgres@localhost/benchmark
  jobs:
      - FRAMEWORK=javascript.iotjs-express
      - FRAMEWORK=javascript.nanoexpress
      - FRAMEWORK=javascript.moleculer
      - FRAMEWORK=javascript.restana
      - FRAMEWORK=javascript.nestjs-fastify
      - FRAMEWORK=javascript.fastify
      - FRAMEWORK=javascript.nanoexpress-pro
      - FRAMEWORK=javascript.sails
      - FRAMEWORK=javascript.hapi
      - FRAMEWORK=javascript.restify
      - FRAMEWORK=javascript.express
      - FRAMEWORK=javascript.polkadot
      - FRAMEWORK=javascript.polka
      - FRAMEWORK=javascript.nestjs-express
      - FRAMEWORK=javascript.turbo_polka
      - FRAMEWORK=javascript.sifrr
      - FRAMEWORK=javascript.koa
      - FRAMEWORK=javascript.0http
      - FRAMEWORK=javascript.foxify
      - FRAMEWORK=javascript.muneem
      - FRAMEWORK=javascript.rayo
      - FRAMEWORK=javascript.feathersjs
      - FRAMEWORK=julia.merly
      - FRAMEWORK=ruby.syro
      - FRAMEWORK=ruby.hanami-api
      - FRAMEWORK=ruby.sinatra
      - FRAMEWORK=ruby.rails
      - FRAMEWORK=ruby.flame
      - FRAMEWORK=ruby.rack-routing
      - FRAMEWORK=ruby.camping
      - FRAMEWORK=ruby.roda
      - FRAMEWORK=ruby.agoo
      - FRAMEWORK=ruby.cuba
      - FRAMEWORK=ruby.hanami
      - FRAMEWORK=ruby.grape
      - FRAMEWORK=ruby.rack_app
      - FRAMEWORK=cpp.evhtp
      - FRAMEWORK=cpp.drogon
      - FRAMEWORK=c.kore
      - FRAMEWORK=c.agoo-c
      - FRAMEWORK=perl.dancer2
      - FRAMEWORK=nim.jester
      - FRAMEWORK=nim.httpbeast
      - FRAMEWORK=kotlin.ktor
      - FRAMEWORK=kotlin.kooby
      - FRAMEWORK=scala.http4s
      - FRAMEWORK=scala.akkahttp
      - FRAMEWORK=elixir.phoenix
      - FRAMEWORK=elixir.plug
      - FRAMEWORK=elixir.cowboy_stream
      - FRAMEWORK=elixir.cowboy
      - FRAMEWORK=crystal.spider-gazelle
      - FRAMEWORK=crystal.shivneri
      - FRAMEWORK=crystal.athena
      - FRAMEWORK=crystal.amber
      - FRAMEWORK=crystal.router.cr
      - FRAMEWORK=crystal.orion
      - FRAMEWORK=crystal.lucky
      - FRAMEWORK=crystal.onyx
      - FRAMEWORK=crystal.kemal
      - FRAMEWORK=crystal.grip
      - FRAMEWORK=crystal.toro
      - FRAMEWORK=php.slim
      - FRAMEWORK=php.ice
      - FRAMEWORK=php.chubbyphp
      - FRAMEWORK=php.yii
      - FRAMEWORK=php.laravel
      - FRAMEWORK=php.nette
      - FRAMEWORK=php.sw-fw-less
      - FRAMEWORK=php.lumen
      - FRAMEWORK=php.imi
      - FRAMEWORK=php.ubiquity
      - FRAMEWORK=php.mezzio
      - FRAMEWORK=php.swoft
      - FRAMEWORK=php.hamlet
      - FRAMEWORK=php.simps
      - FRAMEWORK=php.siler-swoole
      - FRAMEWORK=php.hyperf
      - FRAMEWORK=php.symfony
      - FRAMEWORK=php.one-fpm
      - FRAMEWORK=php.siler
      - FRAMEWORK=php.one
      - FRAMEWORK=php.laminas
      - FRAMEWORK=php.workerman
      - FRAMEWORK=php.phalcon
      - FRAMEWORK=php.basicphp
      - FRAMEWORK=php.yii-swoole
      - FRAMEWORK=php.spiral
      - FRAMEWORK=fsharp.suave
      - FRAMEWORK=java.micronaut
      - FRAMEWORK=java.spring-framework
      - FRAMEWORK=java.spring-boot
      - FRAMEWORK=java.jooby
      - FRAMEWORK=java.rapidoid
      - FRAMEWORK=java.act
      - FRAMEWORK=java.javalin
      - FRAMEWORK=java.blade
      - FRAMEWORK=csharp.aspnetcore
      - FRAMEWORK=rust.nickel
      - FRAMEWORK=rust.gotham
      - FRAMEWORK=rust.iron
      - FRAMEWORK=rust.actix
      - FRAMEWORK=python.sanic
      - FRAMEWORK=python.pyramid
      - FRAMEWORK=python.emmett
      - FRAMEWORK=python.masonite
      - FRAMEWORK=python.fastapi
      - FRAMEWORK=python.tornado
      - FRAMEWORK=python.molten
      - FRAMEWORK=python.nameko
      - FRAMEWORK=python.starlette
      - FRAMEWORK=python.cyclone
      - FRAMEWORK=python.clastic
      - FRAMEWORK=python.falcon
      - FRAMEWORK=python.quart
      - FRAMEWORK=python.hug
      - FRAMEWORK=python.blacksheep
      - FRAMEWORK=python.apidaora
      - FRAMEWORK=python.cherrypy
      - FRAMEWORK=python.flask
      - FRAMEWORK=python.django
      - FRAMEWORK=python.klein
      - FRAMEWORK=python.asgineer
      - FRAMEWORK=python.responder
      - FRAMEWORK=python.aiohttp
      - FRAMEWORK=python.bottle
      - FRAMEWORK=clojure.luminus
      - FRAMEWORK=clojure.coast
      - FRAMEWORK=pony.jennet
      - FRAMEWORK=haskell.servant
      - FRAMEWORK=dart.aqueduct
      - FRAMEWORK=swift.kitura
      - FRAMEWORK=swift.swifter
      - FRAMEWORK=swift.kitura-nio
      - FRAMEWORK=swift.vapor
      - FRAMEWORK=swift.perfect
      - FRAMEWORK=go.air
      - FRAMEWORK=go.echo
      - FRAMEWORK=go.webgo
      - FRAMEWORK=go.gf
      - FRAMEWORK=go.httprouter
      - FRAMEWORK=go.tango
      - FRAMEWORK=go.gorouter-fasthttp
      - FRAMEWORK=go.fasthttp
      - FRAMEWORK=go.aero
      - FRAMEWORK=go.gramework
      - FRAMEWORK=go.beego
      - FRAMEWORK=go.mars
      - FRAMEWORK=go.chi
      - FRAMEWORK=go.router
      - FRAMEWORK=go.goroute
      - FRAMEWORK=go.fiber
      - FRAMEWORK=go.gorilla-mux
      - FRAMEWORK=go.gin
      - FRAMEWORK=go.kami
      - FRAMEWORK=go.gorouter
      - FRAMEWORK=go.violetear
      - FRAMEWORK=go.fasthttprouter
      - FRAMEWORK=go.rte
      - FRAMEWORK=go.atreugo

before_script:
  - psql -c 'CREATE DATABASE benchmark;' -U postgres;
  - psql -U postgres -d benchmark < .ci/dump.sql

script:
  - shards install
  - shards build
  - bin/make config --without-sieger --keep
  - travis_wait travis_retry bin/neph ${FRAMEWORK} --mode=CI
  - sleep 5
  - crystal spec

# Push on docker registry if tests are OK
# This does not work on forks
#after_success: if [ ${TRAVIS_REPO_SLUG} == "the-benchmarker/web-frameworks" ]; then bash .ci/docker_release.sh ; fi

notifications:
  email: false
