# Use latest ubuntu LTS (18.04)
dist: bionic

services:
  - docker # Use docker to containerize frameworks
  - postgresql # Use postgresql to store data

# This tool is written in crystal
language: crystal

env:
  global:
    - DATABASE_URL="postgresql://postgres@localhost/benchmark"
  jobs:
    - FRAMEWORK=httpbeast
    - FRAMEWORK=jester
    - FRAMEWORK=phoon
    - FRAMEWORK=kore
    - FRAMEWORK=agoo-c
    - FRAMEWORK=coast
    - FRAMEWORK=cowboy_stream
    - FRAMEWORK=phoenix
    - FRAMEWORK=cowboy
    - FRAMEWORK=plug
    - FRAMEWORK=nickel
    - FRAMEWORK=iron
    - FRAMEWORK=gotham
    - FRAMEWORK=merly
    - FRAMEWORK=evhtp
    - FRAMEWORK=drogon
    - FRAMEWORK=kemal
    - FRAMEWORK=spider-gazelle
    - FRAMEWORK=router.cr
    - FRAMEWORK=amber
    - FRAMEWORK=athena
    - FRAMEWORK=grip
    - FRAMEWORK=raze
    - FRAMEWORK=onyx
    - FRAMEWORK=lucky
    - FRAMEWORK=orion
    - FRAMEWORK=toro
    - FRAMEWORK=rails
    - FRAMEWORK=grape
    - FRAMEWORK=flame
    - FRAMEWORK=agoo
    - FRAMEWORK=roda
    - FRAMEWORK=rack-routing
    - FRAMEWORK=syro
    - FRAMEWORK=sinatra
    - FRAMEWORK=camping
    - FRAMEWORK=plezi
    - FRAMEWORK=hanami
    - FRAMEWORK=cuba
    - FRAMEWORK=akkahttp
    - FRAMEWORK=http4s
    - FRAMEWORK=gramework
    - FRAMEWORK=fasthttprouter
    - FRAMEWORK=router
    - FRAMEWORK=gin
    - FRAMEWORK=echo
    - FRAMEWORK=aero
    - FRAMEWORK=webgo
    - FRAMEWORK=chi
    - FRAMEWORK=mars
    - FRAMEWORK=air
    - FRAMEWORK=gorouter
    - FRAMEWORK=kami
    - FRAMEWORK=fasthttp
    - FRAMEWORK=goroute
    - FRAMEWORK=atreugo
    - FRAMEWORK=gorilla-mux
    - FRAMEWORK=violetear
    - FRAMEWORK=rte
    - FRAMEWORK=gorouter-fasthttp
    - FRAMEWORK=fiber
    - FRAMEWORK=gf
    - FRAMEWORK=httprouter
    - FRAMEWORK=beego
    - FRAMEWORK=aspnetcore
    - FRAMEWORK=imi
    - FRAMEWORK=swoft
    - FRAMEWORK=laravel
    - FRAMEWORK=lumen
    - FRAMEWORK=slim
    - FRAMEWORK=hyperf
    - FRAMEWORK=one-fpm
    - FRAMEWORK=zend-framework
    - FRAMEWORK=phalcon
    - FRAMEWORK=zend-expressive
    - FRAMEWORK=one
    - FRAMEWORK=ubiquity
    - FRAMEWORK=sw-fw-less
    - FRAMEWORK=basicphp
    - FRAMEWORK=symfony
    - FRAMEWORK=spiral
    - FRAMEWORK=hamlet
    - FRAMEWORK=yii
    - FRAMEWORK=workerman
    - FRAMEWORK=cherrypy
    - FRAMEWORK=apidaora
    - FRAMEWORK=responder
    - FRAMEWORK=asgineer
    - FRAMEWORK=quart
    - FRAMEWORK=emmett
    - FRAMEWORK=hug
    - FRAMEWORK=pyramid
    - FRAMEWORK=blacksheep
    - FRAMEWORK=starlette
    - FRAMEWORK=clastic
    - FRAMEWORK=aiohttp
    - FRAMEWORK=falcon
    - FRAMEWORK=molten
    - FRAMEWORK=flask
    - FRAMEWORK=fastapi
    - FRAMEWORK=django
    - FRAMEWORK=klein
    - FRAMEWORK=sanic
    - FRAMEWORK=bottle
    - FRAMEWORK=masonite
    - FRAMEWORK=tornado
    - FRAMEWORK=cyclone
    - FRAMEWORK=nameko
    - FRAMEWORK=ktor
    - FRAMEWORK=micronaut
    - FRAMEWORK=rapidoid
    - FRAMEWORK=spring-framework
    - FRAMEWORK=act
    - FRAMEWORK=spring-boot
    - FRAMEWORK=javalin
    - FRAMEWORK=dancer2
    - FRAMEWORK=suave
    - FRAMEWORK=restana
    - FRAMEWORK=express
    - FRAMEWORK=muneem
    - FRAMEWORK=iotjs-express
    - FRAMEWORK=polka
    - FRAMEWORK=fastify
    - FRAMEWORK=nanoexpress
    - FRAMEWORK=turbo_polka
    - FRAMEWORK=foxify
    - FRAMEWORK=0http
    - FRAMEWORK=polkadot
    - FRAMEWORK=rayo
    - FRAMEWORK=koa
    - FRAMEWORK=moleculer
    - FRAMEWORK=hapi
    - FRAMEWORK=restify
    - FRAMEWORK=sifrr
    - FRAMEWORK=perfect
    - FRAMEWORK=vapor
    - FRAMEWORK=swifter
    - FRAMEWORK=kitura-nio
    - FRAMEWORK=kitura

before_script:
  - psql -c 'CREATE DATABASE benchmark;' -U postgres;
  - psql -U postgres -d benchmark < .ci/dump.sql

script:
  - shards install
  - shards build
  - bin/make config --without-sieger --keep
  - travis_wait 25 bin/neph ${FRAMEWORK} --mode=CI
  - crystal spec

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p ${DOCKER_PASSWORD} && docker tag ${FRAMEWORK} ${DOCKER_USERNAME}/${FRAMEWORK} && docker push ${DOCKER_USERNAME}/${FRAMEWORK}

notifications:
  email: false
