services:
  - docker
  - redis


language: crystal

env:
  matrix:
    - FRAMEWORK=aspnetcore
    - FRAMEWORK=akkahttp
    - FRAMEWORK=evhtp
    - FRAMEWORK=symfony
    - FRAMEWORK=laravel
    - FRAMEWORK=tornado
    - FRAMEWORK=sanic
    - FRAMEWORK=japronto
    - FRAMEWORK=flask
    - FRAMEWORK=vibora
    - FRAMEWORK=django
    - FRAMEWORK=bottle
    - FRAMEWORK=mofuw
    - FRAMEWORK=act
    - FRAMEWORK=rails
    - FRAMEWORK=rack-routing
    - FRAMEWORK=sinatra
    - FRAMEWORK=hanami
    - FRAMEWORK=roda
    - FRAMEWORK=flame
    - FRAMEWORK=raze
    - FRAMEWORK=kemal
    - FRAMEWORK=spider-gazelle
    - FRAMEWORK=prism
    - FRAMEWORK=lucky
    - FRAMEWORK=amber
    - FRAMEWORK=router.cr
    - FRAMEWORK=kitura
    - FRAMEWORK=perfect
    - FRAMEWORK=vapor
    - FRAMEWORK=gin
    - FRAMEWORK=fasthttprouter
    - FRAMEWORK=echo
    - FRAMEWORK=iris
    - FRAMEWORK=gorilla-mux
    - FRAMEWORK=nickel
    - FRAMEWORK=actix-web
    - FRAMEWORK=rocket
    - FRAMEWORK=iron
    - FRAMEWORK=restify
    - FRAMEWORK=express
    - FRAMEWORK=hapi
    - FRAMEWORK=fastify
    - FRAMEWORK=koa
    - FRAMEWORK=polka
    - FRAMEWORK=rayo

script:
  - shards build
  - bin/neph ${FRAMEWORK}
  - crystal spec

notifications:
  email: false
