# Use latest ubuntu LTS (18.04)
dist: bionic

services:
  - docker # Use docker to containerize frameworks
  - redis # Use redis to store data

# This tool is written in crystal
language: crystal

cache:
  directories:
  - docker_images

before_install:
  - docker load -i docker_images/images.tar || true

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

env:
  matrix:
    - FRAMEWORK=agoo-c
    - FRAMEWORK=kore
    - FRAMEWORK=coast
    - FRAMEWORK=drogon
    - FRAMEWORK=evhtp
    - FRAMEWORK=amber
    - FRAMEWORK=athena
    - FRAMEWORK=kemal
    - FRAMEWORK=lucky
    - FRAMEWORK=onyx
    - FRAMEWORK=orion
    - FRAMEWORK=raze
    - FRAMEWORK=router.cr
    - FRAMEWORK=spider-gazelle
    - FRAMEWORK=toro
    - FRAMEWORK=aspnetcore
    - FRAMEWORK=suave
    - FRAMEWORK=air
    - FRAMEWORK=atreugo
    - FRAMEWORK=beego
    - FRAMEWORK=chi
    - FRAMEWORK=echo
    - FRAMEWORK=fasthttprouter
    - FRAMEWORK=fasthttp
    - FRAMEWORK=gf
    - FRAMEWORK=gin
    - FRAMEWORK=gorilla-mux
    - FRAMEWORK=goroute
    - FRAMEWORK=gorouter-fasthttp
    - FRAMEWORK=gorouter
    - FRAMEWORK=gramework
    - FRAMEWORK=kami
    - FRAMEWORK=rte
    - FRAMEWORK=violetear
    - FRAMEWORK=webgo
    - FRAMEWORK=act
    - FRAMEWORK=javalin
    - FRAMEWORK=rapidoid
    - FRAMEWORK=spring-boot
    - FRAMEWORK=ktor
    - FRAMEWORK=httpbeast
    - FRAMEWORK=jester
    - FRAMEWORK=0http
    - FRAMEWORK=express
    - FRAMEWORK=fastify
    - FRAMEWORK=foxify
    - FRAMEWORK=hapi
    - FRAMEWORK=iotjs-express
    - FRAMEWORK=koa
    - FRAMEWORK=moleculer
    - FRAMEWORK=muneem
    - FRAMEWORK=polka
    - FRAMEWORK=polkadot
    - FRAMEWORK=rayo
    - FRAMEWORK=restana
    - FRAMEWORK=restify
    - FRAMEWORK=sifrr
    - FRAMEWORK=turbo_polka
    - FRAMEWORK=dancer2
    - FRAMEWORK=basicphp
    - FRAMEWORK=hyperf
    - FRAMEWORK=imi
    - FRAMEWORK=laravel
    - FRAMEWORK=lumen
    - FRAMEWORK=one
    - FRAMEWORK=slim
    - FRAMEWORK=spiral
    - FRAMEWORK=swoft
    - FRAMEWORK=symfony
    - FRAMEWORK=zend-expressive
    - FRAMEWORK=zend-framework
    - FRAMEWORK=aiohttp
    - FRAMEWORK=asgineer
    - FRAMEWORK=blacksheep
    - FRAMEWORK=bocadillo
    - FRAMEWORK=bottle
    - FRAMEWORK=cherrypy
    - FRAMEWORK=clastic
    - FRAMEWORK=cyclone
    - FRAMEWORK=django
    - FRAMEWORK=falcon
    - FRAMEWORK=fastapi
    - FRAMEWORK=flask
    - FRAMEWORK=hug
    - FRAMEWORK=japronto
    - FRAMEWORK=masonite
    - FRAMEWORK=molten
    - FRAMEWORK=nameko
    - FRAMEWORK=quart
    - FRAMEWORK=responder
    - FRAMEWORK=sanic
    - FRAMEWORK=starlette
    - FRAMEWORK=tornado
    - FRAMEWORK=agoo
    - FRAMEWORK=camping
    - FRAMEWORK=cuba
    - FRAMEWORK=flame
    - FRAMEWORK=grape
    - FRAMEWORK=hanami
    - FRAMEWORK=plezi
    - FRAMEWORK=rack-routing
    - FRAMEWORK=rails
    - FRAMEWORK=roda
    - FRAMEWORK=sinatra
    - FRAMEWORK=syro
    - FRAMEWORK=actix-web
    - FRAMEWORK=gotham
    - FRAMEWORK=iron
    - FRAMEWORK=nickel
    - FRAMEWORK=akkahttp
    - FRAMEWORK=http4s
    - FRAMEWORK=kitura-nio
    - FRAMEWORK=kitura
    - FRAMEWORK=perfect
    - FRAMEWORK=swifter
    - FRAMEWORK=vapor
    - FRAMEWORK=sw-fw-less

script:
  - shards install
  - shards build
  - bin/make config --without-sieger
  - bin/neph ${FRAMEWORK}
  - crystal spec

notifications:
  email: false
