services:
  - docker
  - redis


language: crystal

env:
  matrix:
    - FRAMEWORK=aspnetcore
    - FRAMEWORK=akkahttp
    - FRAMEWORK=http4s
    - FRAMEWORK=evhtp
    - FRAMEWORK=slim
    - FRAMEWORK=symfony
    - FRAMEWORK=laravel
    - FRAMEWORK=tornado
    - FRAMEWORK=sanic
    - FRAMEWORK=japronto
    - FRAMEWORK=flask
    - FRAMEWORK=vibora
    - FRAMEWORK=django
    - FRAMEWORK=bottle
    - FRAMEWORK=aiohttp
    - FRAMEWORK=quart
    - FRAMEWORK=cyclone
    - FRAMEWORK=mofuw
    - FRAMEWORK=jester
    - FRAMEWORK=act
    - FRAMEWORK=rails
    - FRAMEWORK=rack-routing
    - FRAMEWORK=sinatra
    - FRAMEWORK=hanami
    - FRAMEWORK=roda
    - FRAMEWORK=flame
    - FRAMEWORK=raze
    - FRAMEWORK=kemal
    - FRAMEWORK=spider-gazelle
    - FRAMEWORK=lucky
    - FRAMEWORK=amber
    - FRAMEWORK=router.cr
    - FRAMEWORK=orion
    - FRAMEWORK=kitura
    - FRAMEWORK=perfect
    - FRAMEWORK=vapor
    - FRAMEWORK=gin
    - FRAMEWORK=fasthttprouter
    - FRAMEWORK=echo
    - FRAMEWORK=iris
    - FRAMEWORK=beego
    - FRAMEWORK=gorilla-mux
    - FRAMEWORK=muxie
    - FRAMEWORK=nickel
    - FRAMEWORK=actix-web
    - FRAMEWORK=rocket
    - FRAMEWORK=iron
    - FRAMEWORK=restify
    - FRAMEWORK=express
    - FRAMEWORK=hapi
    - FRAMEWORK=fastify
    - FRAMEWORK=koa
    - FRAMEWORK=polka
    - FRAMEWORK=rayo
    - FRAMEWORK=turbo_polka
    - FRAMEWORK=kore

before_script:
  # Install yaml lint tool to check syntax
  - sudo pip install yamllint

  # Check yaml syntax for all yaml files
  - find . -type f -name '*.yml' -or -name '*.yaml' -exec yamllint {} \;

script:
  - shards build
  - bin/neph ${FRAMEWORK} --mode=CI --seq
  - crystal spec

notifications:
  email: false
