# Routes
index:
  path: /
  controller: App\Controller\DefaultController:index
  methods: GET

get_user:
  path: /user/{userId}
  controller: App\Controller\DefaultController:getUser
  methods: GET

post_user:
  path: /user
  controller: App\Controller\DefaultController:createUser
  methods: POST