framework:
  website: coast.swlkr.com
  version: 1.0

  environment:
    COAST_ENV: prod

  build:
    - mkdir classes && clj -e "(compile 'server)" && clojure -Auberjar --main-class server

  binaries:
    - coast.jar

  command: java -jar coast.jar 3000
