framework:
  website: undertow.io
  version: 2.0

build:
  - mvn package

files:
  - target/server-jar-with-dependencies.jar

binaries:
  - target/server-jar-with-dependencies.jar

command: /usr/bin/java -XX:-RelaxAccessControlCheck -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/server-jar-with-dependencies.jar
