framework:
  website: imiphp.com
  version: 2.0

  extensions:
    - redis

  engines:
    - swoole

language:
  version: 8.4
  engines:
    swoole:
      command: php vendor/bin/imi-swoole swoole/start
