framework:
  website: phalcon.io
  version: 5.0

  extensions:
    - psr

  before_bootstrap:
    - mkdir -p /usr/src/php/ext/phalcon
    - curl -fsSL https://github.com/phalcon/cphalcon/releases/download/v5.0.0alpha7/phalcon-pecl.tgz | tar xvz -C "/usr/src/php/ext/phalcon" --strip 1
    - docker-php-ext-install phalcon

  nginx_conf:
    - |
      location /{\n\
          rewrite ^/(.*)$ /index.php?_url=$1 last;\n\
      }\n\
    - |
      location = /index.php {\n\
        fastcgi_pass unix:/var/run/php-fpm.sock;\n\
        fastcgi_param   SCRIPT_FILENAME         $document_root/index.php;\n\
        include fastcgi_params;\n\
      }\n\
