framework:
  website: phalcon.io
  version: 5.3

  extensions:
    - psr
    - phalcon

  nginx_conf:
    - |
      location /{\n\
          rewrite ^/(.*)$ /index.php?_url=$1 last;\n\
      }\n\
    - |
      location = /index.php {\n\
        fastcgi_pass unix:/var/run/php-fpm.sock;\n\
        fastcgi_param   SCRIPT_FILENAME         $document_root/index.php;\n\
        include fastcgi_params;\n\
      }\n\
