framework:
  website: sifrr.github.io/sifrr/#/./packages/server/sifrr-server/
  version: 0.0

deps:
  - git
  - "@development-tools"
  - nodejs

alpine-deps:
  - gcompat # required by uWebSocket
  - git
