framework:
  website: hug.rest
  unsecure: true
  github: hugapi/hug
  version: 2.6

  engines:
    - uwsgi
    - gunicorn
    - waitress

  # TODO : override unused PYTHON_APP in generated dockerfile

language:
  engines:
    uwsgi:
      command: uwsgi 0.0.0.0:3000 --wsgi-file server.py --callable __hug_wsgi__
