framework:
  website: activej.io
  version: 5.4

build:
  - mvn clean package

binaries:
  - target/benchmark.jar

command: >
  /usr/bin/java -server
  -XX:+UseNUMA -XX:+UseParallelGC -XX:-UseBiasedLocking -XX:+UseStringDeduplication
  -jar target/benchmark.jar benchmark.App
