language:
  version: "1.10"
  website: gleam.run

  files:
    - gleam.toml
    - "**/*.gleam"

  engines:
    default:
      command: /opt/web/build/erlang-shipment/entrypoint.sh  run

framework:
  engines:
    - default
