framework:
  github: RobertoPrevato/BlackSheep
  version: 0.2

command: >
  gunicorn  \ 
    --log-level warning  \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class uvicorn.workers.UvicornWorker  \
      server:app
