[package]
name = "server"
version = "0.1.0"
authors = ["taicsuzu <taicsuzu@yahoo-corp.jp>"]

[dependencies]
nickel = "0.11.0"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
incremental = false
