framework:
  github: nedpals/vex
  version: 0.3

  bootstrap:
    - v install nedpals.vex
    - cd /opt/vlang && git fetch --all --tags && git checkout tags/weekly.2023.48 && make && v -version && cd /app

  build_flags:
    - -prod -cc clang
