framework:
  website: trypyramid.com
  version: 2.0

command: >
  gunicorn  \
    --log-level warning  \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class gevent \
      server:app
