framework:
  website: aiohttp.readthedocs.io
  version: 3.6

command: >
  gunicorn -c config.py \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class aiohttp.GunicornUVLoopWebWorker \
      server:app
