name = "buffalo_framework"
bin = "bin/buffalo_framework"
vcs = "git"
with_pop = false
with_sqlite = false
with_dep = false
with_webpack = false
with_nodejs = false
with_yarn = false
with_docker = true
with_grifts = true
as_web = false
as_api = true
