framework:
  github: chubbyjs/chubbyjs-framework
  version: 1.1

  engines:
    - node
    - uwebsockets

  bootstrap:
    - npm install # workaround
    - npm -g install typescript
    - tsc

  files:
    - app.ts
    - package.json
    - tsconfig.json
