language:
  version: 11

  files:
    - CMakeLists.txt
    - "**/*.h"
    - "**/*.hpp"
    - "**/*.cc"
    - "**/*.cpp"
    - "**/*.cmake"

  engines:
    default:
      command: /opt/web/simple
  
framework:
  engines:
    - default
