framework:
  github: hhxsv5/laravel-s
  version: 3.7

php_mod:
  - pcntl

php_ext:
  - openswoole

environment:
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: base64:txfHNf/SOo222Rm8I39Urb9SmvUy+nuAF98t/ukF0lk=

before_command:
  - mkdir storage

command: php bin/laravels start
