framework:
  website: www.palletsprojects.com/p/flask/
  version: 3.0

  engines:
    - gunicorn
    - uwsgi
    - waitress
    - granian

language:
  engines:
    granian:
      environment:
        INTERFACE: wsgi