framework:
  github: an-tao/drogon
  version: 1.7

provider:
  default:
    language: 14/17

build_deps:
  - libjsoncpp-dev
  - libssl-dev
  - zlib1g-dev
  - libbrotli-dev
  - uuid-dev

bin_deps:
  - libjsoncpp1
  - openssl
  - zlib1g
  - libbrotli1
  - libuuid1

binaries:
  - build/drogon_benchmark

download:
  - git clone --branch v1.7.0 https://github.com/an-tao/drogon
  - cd drogon && git submodule update --init

build:
  - mkdir build
  - cd build && cmake -DCMAKE_BUILD_TYPE=release ..
  - cd build && make

files:
  - config.json

command: /opt/web/build/drogon_benchmark /opt/web/config.json
