framework:
  website: codeigniter.com
  version: 4.3

  modules:
    - intl

  environment:
    CI_ENVIRONMENT: production

  bootstrap:
    - mkdir writable/cache -p
    - chown -R www-data:www-data writable/cache
