framework:
  website: codeigniter.com
  version: 4.0

php_mod:
  - curl
  - intl
  - json
  - mbstring

environment:
  CI_ENVIRONMENT: production

before_command:
  - mkdir writable/cache -p
  - chown -R www-data:www-data writable/cache
