framework:
  website: index-py.abersheeran.com
  version: 0.16

command: >
  gunicorn  \
    --log-level warning  \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class uvicorn.workers.UvicornWorker  \
      server:app
