framework:
  website: bottlepy.org
  version: 0.12

  engines:
    - gunicorn
    - wsgiref
    - bjoern
    - cheroot
    - waitress
    - gunicorn

language:
  engines:
    wsgiref:
      command: python server.py 3000
    bjoern:
      bootstrap:
        - pip install bjoern
      command: python server.py 3000 bjoern
    cheroo3:
      bootstrap:
        - pip install cheroot
      command: python server.py 3000 cheroot
    waitress:
      bootstrap:
        - pip install waitress
      command: python server.py 3000 waitress
    gunicorn:
      bootstrap:
        - pip install gunicorn
      command: python server.py 3000 gunicorn
