framework:
  website: bottlepy.org
  version: 0.12

command: >
  gunicorn  \
    --log-level warning  \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class gevent \
      server:app
