language:
  version: 17

  files:
    - src/**/*.java
    - pom.xml
    - src/**/*.properties
    - src/**/*.xml
    - src/**/*.jsp

  fix:
    - ln -sfv /usr/local/openjdk-17/bin/java /usr/bin/java

  binaries:
    - target/benchmark-1.0.0.jar

  deps:
    - java-17-openjdk

  engines:
    default:
      command: >
        /usr/bin/java
        -XX:+UseNUMA -XX:+UseParallelGC 
        -jar /opt/web/target/benchmark-1.0.0.jar

framework:
  engines:
    - default
