framework:
  website: baize.aber.sh
  version: 0.13

command: >
  gunicorn \
    --log-level warning \
    --bind 0.0.0.0:3000 \
    --reuse-port \
    --workers $(nproc) \
    --worker-class meinheld.gmeinheld.MeinheldWorker \
      server:app
