framework:
  website: struts.apache.org
  version: 6.2

  build:
    - mvn clean package

  binaries:
    - target/benchmark-1.0.0-standalone.jar

  command: java -XX:+UseNUMA -XX:+UseParallelGC -jar target/benchmark-1.0.0-standalone.jar --port 3000
