framework:
  website: rubyonrails.org
  version: 7.2

  bootstrap:
    - mkdir -p tmp/pids

  environment:
    RAILS_ENV: production
    RAILS_LOG_LEVEL: fatal
    # Rails enables YJIT after the app has initialized 
    RUBY_YJIT_ENABLE: 0
