
[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core"]

[project]
name='server'
version = '1.0.0'
description = "Simple benchmark implementation"
dependencies = ["panther>=4.3.2,<4.3.3"]
