provider:
 default:
   language: 1.7
   image-version: 1.7.3

framework:
  github: ujjwalguptaofficial/shivneri
  version: 0.18

build_opts: '--link-flags "-lxml2 -llzma"'

environment:
  CRYSTAL_ENV: production
