framework:
  website: github.com/emmett-framework/emmett
  version: "2.0.0a5"

build_deps:
  - libffi-dev
  - git

# cryptography could not be install on alpine
# @see https://github.com/pyca/cryptography/issues/4264#issuecomment-392781146
fixes:
  - apk del libressl-dev
  - apk add openssl-dev
  - pip install cryptography==2.2.2
  - apk del openssl-dev
  - apk add libressl-dev


command: >
  gunicorn  \
    --log-level warning  \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class emmett.asgi.workers.EmmettWorker  \
      server:app
