framework:
  website: vapor.codes
  version: 4.14
  name: vapor

options: serve
environment:
   SERVER_HOSTNAME: 0.0.0.0
   SERVER_PORT: 3000
   VAPOR_ENV: production

command: /opt/web/.build/release/server serve
