version: 1

update_configs:

    #############################
    ###### RUBY FRAMEWORKS ######
    #############################

  - package_manager: "ruby:bundler"
    update_schedule: "live"
    directory: "/ruby/sinatra"
    default_labels:
      - language:ruby

  - package_manager: "ruby:bundler"
    update_schedule: "live"
    directory: "/ruby/rack-routing"
    default_labels:
      - language:ruby

  - package_manager: "ruby:bundler"
    update_schedule: "live"
    directory: "/ruby/hanami"
    default_labels:
      - language:ruby
    
  - package_manager: "ruby:bundler"
    update_schedule: "live"
    directory: "/ruby/agoo"
    default_labels:
      - language:ruby

  - package_manager: "ruby:bundler"
    update_schedule: "live"
    directory: "/ruby/roda"
    default_labels:
      - language:ruby
    
  - package_manager: "ruby:bundler"
    update_schedule: "live"
    directory: "/ruby/flame"
    default_labels:
      - language:ruby

  - package_manager: "ruby:bundler"
    update_schedule: "live"
    directory: "/ruby/rails"
    default_labels:
      - language:ruby
    
    #########################
    #### RUST FRAMEWORKS ####
    #########################

  - package_manager: "rust:cargo"
    update_schedule: "live"
    directory: "/rust/nickel"
    default_labels:
      - language:rust
    
  - package_manager: "rust:cargo"
    update_schedule: "live"
    directory: "/rust/iron"
    default_labels:
      - language:rust
    
  - package_manager: "rust:cargo"
    update_schedule: "live"
    directory: "/rust/rocket"
    default_labels:
      - language:rust
    
  - package_manager: "rust:cargo"
    update_schedule: "live"
    directory: "/rust/actix-web"
    default_labels:
      - language:rust
    
  - package_manager: "rust:cargo"
    update_schedule: "live"
    directory: "/rust/gotham"
    default_labels:
      - language:rust
    
    ###########################
    #### PYTHON FRAMEWORKS ####
    ###########################

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/japronto"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/flask"
    default_labels:
      - language:python
    
  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/falcon"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/responder"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/cyclone"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/starlette"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/hug"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/django"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/sanic"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/bottle"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/bocadillo"
    default_labels:
      - language:python
    default_reviewers:
      - florimondmanca

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/fastapi"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/tornado"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/molten"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/aiohttp"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/vibora"
    default_labels:
      - language:python

  - package_manager: "python"
    update_schedule: "live"
    directory: "/python/quart"
    default_labels:
      - language:python
  
    ############################
    ###### PHP FRAMEWORKS ######
    ############################

  - package_manager: "php:composer"
    update_schedule: "live"
    directory: "/php/zend-framework"
    default_labels:
      - language:php

  - package_manager: "php:composer"
    update_schedule: "live"
    directory: "/php/zend-expressive"
    default_labels:
      - language:php

  - package_manager: "php:composer"
    update_schedule: "live"
    directory: "/php/slim"
    default_labels:
      - language:php

  - package_manager: "php:composer"
    update_schedule: "live"
    directory: "/php/symfony"
    default_labels:
      - language:php

  - package_manager: "php:composer"
    update_schedule: "live"
    directory: "/php/laravel"
    default_labels:
      - language:php

  - package_manager: "php:composer"
    update_schedule: "live"
    directory: "/php/lumen"
    default_labels:
      - language:php

    #############################
    ######### JAVASCRIPT ########
    ###### NODE FRAMEWORKS ######
    #############################

  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/foxify"
    default_labels:
      - language:javascript

  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/turbo_polka"
    default_labels:
      - language:javascript

  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/fastify"
    default_labels:
      - language:javascript

  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/hapi"
    default_labels:
      - language:javascript

  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/muneem"
    default_labels:
      - language:javascript

  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/restify"
    default_labels:
      - language:javascript
    
  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/polka"
    default_labels:
      - language:javascript

  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/rayo"
    default_labels:
      - language:javascript

  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/koa"
    default_labels:
      - language:javascript

  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/node/restana"
    default_labels:
      - language:javascript

    ###############################
    ####### JAVA FRAMEWORKS #######
    ###############################

  - package_manager: "java:maven"
    directory: "/java/act"
    update_schedule: "daily"
    default_labels:
      - language:java

    ###############################
    ######## GO FRAMEWORKS ########
    ###############################

  - package_manager: "go:modules"
    directory: "/go/gin"
    update_schedule: "daily"
    default_labels:
      - language:go

  - package_manager: "go:modules"
    directory: "/go/fasthttprouter"
    update_schedule: "daily"
    default_labels:
      - language:go

  - package_manager: "go:modules"
    directory: "/go/beego"
    update_schedule: "daily"
    default_labels:
      - language:go

  - package_manager: "go:modules"
    directory: "/go/gf"
    update_schedule: "daily"
    default_labels:
      - language:go

  - package_manager: "go:modules"
    directory: "/go/echo"
    update_schedule: "daily"
    default_labels:
      - language:go

  - package_manager: "go:modules"
    directory: "/go/iris"
    update_schedule: "daily"
    default_labels:
      - language:go

  - package_manager: "go:modules"
    directory: "/go/muxie"
    update_schedule: "daily"
    default_labels:
      - language:go

  - package_manager: "go:modules"
    directory: "/go/chi"
    update_schedule: "daily"
    default_labels:
      - language:go

  - package_manager: "go:modules"
    directory: "/go/gorilla-mux"
    update_schedule: "daily"
    default_labels:
      - language:go

  - package_manager: "go:modules"
    directory: "/go/kami"
    update_schedule: "daily"
    default_reviewers:
      - guregu
    default_labels:
      - language:go

    
  # Dockefiles
  # This create PR for development environment
  # One per language

  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/node/rayo"
    default_labels:
      - docker

  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/csharp/aspnetcore"
    default_labels:
      - docker
    
  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/elixir/phoenix"
    default_labels:
      - docker
    
  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/scala/http4s"
    default_labels:
      - docker

  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/cpp/evhtp"
    default_labels:
      - docker

  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/php/laravel"
    default_labels:
      - docker
    
  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/python/aiohttp"
    default_labels:
      - docker

  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/c/kore"
    default_labels:
      - docker
    
  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/nim/jester"
    default_labels:
      - docker

  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/java/act"
    default_labels:
      - docker
    
  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/ruby/cuba"
    default_labels:
      - docker
    
  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/swift/vapor"
    default_labels:
      - docker
    
  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/go/gorilla-mux"
    default_labels:
      - docker

  - package_manager: "docker"
    update_schedule: "daily"
    directory: "/rust/iron"
    default_labels:
      - docker
