framework:
  website: eclipse-ee4j.github.io/jersey
  version: "2.40"

  build:
    - mvn package

  files:
    - target/server-jar-with-dependencies.jar

  binaries:
    - target/server-jar-with-dependencies.jar

  command: /usr/bin/java -jar /opt/web/target/server-jar-with-dependencies.jar
