framework:
  github: spiral/framework
  version: 3.16

  engines:
    - road-runner

  bootstrap:
    - php public/index.php configure

language:
  engines:
    road-runner:
      command: ./rr serve
