framework:
  website: javalin.io
  version: 3.8

build: 
  - mvn compile assembly:single

command: >
  /usr/bin/java -server 
  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts 
  -cp /opt/web/target/benchmark-0.0.1-SNAPSHOT-jar-with-dependencies.jar benchmark.javalin.Bench profiles=production
