framework:
  website: javalin.io
  version: 6.0

  build:
    - mvn compile assembly:single

  binaries:
    - target/benchmark-1.0.0-jar-with-dependencies.jar

  command: >
    /usr/bin/java -cp target/benchmark-1.0.0-jar-with-dependencies.jar benchmark.javalin.Bench
