framework:
  github: ohler55/agoo
  version: 2.14

environment:
  # FIXME: how to compute this
  AGOO_WORKER_COUNT: $(nproc)

files:
  - app.rb
  - Gemfile

bootstrap:
  - bundle config set without "development test"
  - bundle config set path "vendor/bundle"
  - bundle install
  - bundle binstubs bundler

command: /opt/web/bin/bundle exec /usr/bin/ruby /opt/web/app.rb
