framework:
  website: adonisjs.com
  version: 5.9

bootstrap:
  - npm install -g typescript
  - npm link typescript
  - node ace build --production

files:
  - .adonisrc.json
  - ace
  - ace-manifest.json
  - package.json
  - "**/*.ts"
  - tsconfig.json

command: pm2-runtime start build/app.js -i $(nproc)
