language:
  version: 3.7
  files:
    - "**/*.gradle"
    - "**/*.scala"
    - "**/*.sbt"
    - "**/*.conf"

  engines:
    default:
      command: /usr/src/app/server-0.1.0-SNAPSHOT/bin/server

framework:
  engines:
    - default
