
[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core"]

[project]
name='server'
version = '1.0.0'
description = "Simple benchmark implementation"
dependencies = ["happyxpy>=4.0,<4.1"]
