framework:
  github: chubbyts/chubbyts-framework
  version: 1.7

build_deps:
  - git # required by uWebSocket

bin_deps:
  - gcompat # required by uWebSocket

before_command:
  - npm -g install typescript
  - tsc

files:
  - app.ts
  - package.json
  - tsconfig.json
