framework:
  website: django-ninja.rest-framework.com
  version: "0.20"

  engines:
    - uvicorn
    - hypercorn
    - daphne

language:
  engines:
    uvicorn:
      command: uvicorn --host 0.0.0.0 --port 3000 --workers $(nproc) app.asgi:application
    hypercorn:
      command: hypercorn --bind 0.0.0.0:3000 --workers $(nproc) app.asgi:application
    daphne:
      command: daphne -b 0.0.0.0 -p 3000 app.asgi:application
