framework:
  website: django-ninja.rest-framework.com
  version: 0.21

command: >
  gunicorn \
    --log-level warning  \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class uvicorn.workers.UvicornWorker  \
      app.asgi:application
