language:
  version: "1.37"

  files:
    - "**/*.d"
    - dub.json
    - dub.selections.json
    - dub.sdl

  engines:
    default:
      command: /opt/web/server

framework:
  engines:
    - default
