language:
  version: 1.30.0

  files:
    - "**/*.d"
    - dub.json
    - dub.selections.json
    - dub.sdl

  engines:
    default:
      command: /usr/src/app/server

framework:
  engines:
    - default
