framework:
  github: sunrise-php/http-router
  version: 2.12
  
build_deps:
  - libevent-dev
  - libsodium-dev

php_mod:
  - sodium
  - sockets

php_ext:
  - event
  - apcu

before_command:
  - ./vendor/bin/rr get-binary

command: ./rr serve
