language:
  version: 1.9

  files:
    - "**/*.gradle"
    - "**/*.kts"
    - "**/*.kt"
    - "**/*.conf"
    - "**/*.properties"

  engines:
    default:
      command: java -server -jar /usr/src/app/build/libs/server.jar

framework:
  engines:
    - default
