provider:
  default:
    language: 1.3

sources:
  - "**/*.kt"
  - "**/*.gradle"
  - "**/*.properties"
  - "**/*.conf"

binaries:
  - build

command: /usr/bin/java -server -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -XX:+AlwaysPreTouch -jar /opt/web/build/libs/my-application.jar

deps:
  - java-11-openjdk
