framework:
  website: jooby.io
  version: 3.0

  build:
    - mvn clean package

  binaries:
    - target/benchmark.jar

  command: >
    /usr/bin/java -server
    -Xms2g -Xmx2g -XX:+UseNUMA -XX:+UseParallelGC
    -jar target/benchmark.jar benchmark.App
