name: CI

on:
  - pull_request
jobs:
  matrix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Install deps
        run: bundle install --jobs 4 --retry 3
      - id: set-matrix
        run: echo "matrix=$(bundle exec rake ci:matrix)" >> "$GITHUB_OUTPUT"
        env:
          FILES: ${{ steps.file_changes.outputs.files }}

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test:
    needs: matrix

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Install deps
        run: bundle install --jobs 4 --retry 3

      - name: Docker version
        run: docker -v

      - name: Configure
        run: bundle exec rake config

      - name: Build
        run: |
          make "build"  -f "${DIRECTORY}/.Makefile"
        env:
          DIRECTORY: ${{ matrix.directory }}
          ENGINE: ${{ matrix.engine }}

      - name: Wait
        run: |
          export CID=`cat ${LANGUAGE}/${FRAMEWORK}/cid-${ENGINE}.txt`
          until [ "`docker inspect -f {{.State.Health.Status}} ${CID}`" = "healthy" ]; do 
            echo "Wait for container to be healthy"
            sleep 1 
          done
        timeout-minutes: 5
        env:
          LANGUAGE: ${{ matrix.language }}
          FRAMEWORK: ${{ matrix.framework }}
          ENGINE: ${{ matrix.engine }}

      - name: Test
        run: bundle exec rspec .spec
        env:
          LANGUAGE: ${{ matrix.language }}
          FRAMEWORK: ${{ matrix.framework }}
          ENGINE: ${{ matrix.engine }}
