name: CI

on:
  - pull_request
jobs:
  matrix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Install deps
        run: bundle install --jobs 4 --retry 3
      - id: set-matrix
        run: echo "::set-output name=matrix::$(bundle exec rake ci:matrix)"
        env:
          FILES: ${{ steps.file_changes.outputs.files }}

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test:
    needs: matrix

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Install deps
        run: bundle install --jobs 4 --retry 3

      - name: Docker version
        run: docker -v

      - name: Configure
        run: bundle exec rake config

      - name: Build
        run: |
          make "build.${ENGINE}"  -f "${DIRECTORY}/.Makefile"
        env:
          DIRECTORY: ${{ matrix.directory }}
          ENGINE: ${{ matrix.engine }}

      - name: Test
        run: bundle exec rspec .spec
        env:
          LANGUAGE: ${{ matrix.language }}
          FRAMEWORK: ${{ matrix.framework }}
          ENGINE: ${{ matrix.engine }}
