---
# Sanitize request for cross site scripting during runtime

# indicate if sanitizer is enabled or not
enabled: ${sanitizer.enabled:true}

# if it is enabled, does body need to be sanitized
sanitizeBody: ${sanitizer.sanitizeBody:true}

# if it is enabled, does header need to be sanitized
sanitizeHeader: ${sanitizer.sanitizeHeader:false}
